(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DAY=86400000, API='https://lexibridge4-deepseek.vercel.app/api/lexi', HEALTH='https://lexibridge4-deepseek.vercel.app/api/health';
const POS=['noun','verb','adjective','adverb','phrase'], POS_ZH={noun:'名词',verb:'动词',adjective:'形容词',adverb:'副词',phrase:'短语',word:'词'};
const LEVEL=['A1','A2','B1','B2','C1','C2'], LANGS=['en','de','fr'];
const LM={en:{name:'English',short:'EN',locale:'en-US'},de:{name:'Deutsch',short:'DE',locale:'de-DE'},fr:{name:'Français',short:'FR',locale:'fr-FR'}};
const STORE='lexibridge4_state_v10';
const BAND=r=>r<=2500?['core','核心 1–2500']:r<=5000?['upper','中高级 2501–5000']:r<=8000?['academic','学术 5001–8000']:['advanced','高级 8001–10000'];
const defaultState=()=>({version:10,settings:{dailyNew:6,reviewCap:90,startRank:2501,languageMode:'all',directionMode:'adaptive',masterReps:5,masterDays:30,pageSize:40,theme:'system',autoReview:true},progress:{},reviews:0,favorites:{},richWords:[],recent:[]});
let state=loadState(), cards=[], byRank=new Map(), byWord=new Map(), filters={band:'all',status:'all',pos:'all',sort:'relevance',q:'',page:1};
let detailCard=null, analysis=null, sense=null, sensePack=null, queue=[], qi=0, currentTask=null;
let studyEpoch=0, detailEpoch=0, searchEpoch=0, advancing=false;
const aMem=new Map(), pMem=new Map(), analysisFlights=new Map(), packFlights=new Map();
let dbp=null;

function loadState(){try{const x=JSON.parse(localStorage.getItem(STORE)||'null');if(!x)return defaultState();const d=defaultState();return {...d,...x,settings:{...d.settings,...(x.settings||{})},progress:x.progress||{},favorites:x.favorites||{},richWords:Array.isArray(x.richWords)?x.richWords:[],recent:Array.isArray(x.recent)?x.recent:[]};}catch{return defaultState();}}
function saveState(){localStorage.setItem(STORE,JSON.stringify(state));}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function norm(s=''){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();}
function toast(msg,ms=2000){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._tm);t._tm=setTimeout(()=>t.classList.remove('show'),ms);}
function db(){return dbp ||= new Promise((resolve,reject)=>{const r=indexedDB.open('lexibridge4-v11-rich',1);r.onupgradeneeded=()=>r.result.createObjectStore('cache');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function cacheGet(k){try{const d=await db();return await new Promise((res,rej)=>{const r=d.transaction('cache','readonly').objectStore('cache').get(k);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error);});}catch{return null;}}
async function cachePut(k,v){try{const d=await db();await new Promise((res,rej)=>{const r=d.transaction('cache','readwrite').objectStore('cache').put(v,k);r.onsuccess=()=>res();r.onerror=()=>rej(r.error);});}catch{}}
async function cacheDel(k){try{const d=await db();await new Promise((res,rej)=>{const r=d.transaction('cache','readwrite').objectStore('cache').delete(k);r.onsuccess=()=>res();r.onerror=()=>rej(r.error);});}catch{}}
const aKey=w=>`analysis:${norm(w)}`, pKey=(w,id)=>`sense:${norm(w)}:${id}`;
async function getAnalysis(word){const k=aKey(word);if(aMem.has(k))return aMem.get(k);const v=await cacheGet(k);if(v)aMem.set(k,v);return v;}
async function putAnalysis(word,v){const k=aKey(word);aMem.set(k,v);await cachePut(k,v);const w=norm(word);if(!state.richWords.includes(w))state.richWords.push(w);saveState();}
async function getPack(word,id){const k=pKey(word,id);if(pMem.has(k))return pMem.get(k);const v=await cacheGet(k);if(v)pMem.set(k,v);return v;}
async function putPack(word,id,v){const k=pKey(word,id);pMem.set(k,v);await cachePut(k,v);}

function makeCard(r,idx){const rank=idx+1,[bid,bl]=BAND(rank),pos=typeof r[1]==='number'?(POS[r[1]]||'word'):String(r[1]||'word');const c={en:String(r[0]||''),pos,level:LEVEL[r[2]]||'C1',rank,band:{id:bid,label:bl},base:{enDef:String(r[4]||''),zh:String(r[5]||''),de:String(r[6]||''),fr:String(r[7]||'')}};c.searchText=norm([c.en,c.base.enDef,c.base.zh,c.base.de,c.base.fr].join(' '));return c;}
function buildCards(){cards=(window.LB4_ROWS||[]).map(makeCard);byRank=new Map(cards.map(c=>[c.rank,c]));byWord=new Map(cards.map(c=>[norm(c.en),c]));$('#buildState').textContent=cards.length===10000?'10,000 词底库已载入 · 词义由 DeepSeek 按需校正':'词库加载 '+cards.length.toLocaleString()+'/10,000';$('#startBtn').disabled=!cards.length;renderHome();checkBackend();}
function directCard(word){const w=word.trim();return {en:w,pos:'word',level:'—',rank:0,band:{id:'custom',label:'AI 直接查询'},base:{enDef:'',zh:'',de:'',fr:''},searchText:norm(w),custom:true};}

async function api(payload){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||`HTTP ${r.status}`);return d.result;}
async function checkBackend(){const pill=$('#backendPill'),txt=$('#backendText');pill.classList.remove('ready','bad');try{const r=await fetch(HEALTH,{cache:'no-store'}),d=await r.json();if(r.ok&&d.ok){pill.classList.add('ready');txt.textContent=(d.models||[]).includes('deepseek-v4-pro')?'Flash 生成 · Pro 终审':'DeepSeek 已连接';}else{pill.classList.add('bad');txt.textContent=d.error||'DeepSeek 未就绪';}}catch{pill.classList.add('bad');txt.textContent='后端未连接';}}
async function ensureAnalysis(c){let a=await getAnalysis(c.en);if(a)return a;const key=norm(c.en);if(analysisFlights.has(key))return analysisFlights.get(key);const job=(async()=>{const base={rank:c.rank,pos:c.pos,englishDefinitionHint:c.base.enDef,zhHint:c.base.zh,deHint:c.base.de,frHint:c.base.fr,note:'这些只是旧词库线索，可能是冷僻义或错误翻译，请独立判断'};const out=await api({action:'analyze',word:c.en,base});if(!Array.isArray(out?.senses)||!out.senses.length)throw new Error('DeepSeek 未返回有效义项');if(out?.word&&norm(out.word)!==norm(c.en))await putAnalysis(out.word,out);await putAnalysis(c.en,out);return out;})();analysisFlights.set(key,job);try{return await job;}finally{if(analysisFlights.get(key)===job)analysisFlights.delete(key);}}
async function ensurePack(c,s,force=false){let p=force?null:await getPack(c.en,s.id);if(p)return p;const key=pKey(c.en,s.id);if(packFlights.has(key))return packFlights.get(key);const job=(async()=>{let out=await api({action:'sense',word:c.en,sense:s});if(state.settings.autoReview){try{out=await api({action:'review',word:c.en,sense:s,pack:out});}catch(e){out.audit=out.audit||{};out.audit.warnings=[...(out.audit.warnings||[]),`二次校对失败：${e.message}`];}}await putPack(c.en,s.id,out);return out;})();packFlights.set(key,job);try{return await job;}finally{if(packFlights.get(key)===job)packFlights.delete(key);}}
async function reviewPack(){const epoch=detailEpoch,card=detailCard,selected=sense,pack=sensePack;if(!card||!selected||!pack)return;setSenseBusy('DeepSeek 正在独立二次校对…');try{const p=await api({action:'review',word:card.en,sense:selected,pack});if(epoch!==detailEpoch||detailCard!==card||sense!==selected)return;sensePack=p;await putPack(card.en,selected.id,p);renderSensePack();toast('二次校对完成');}catch(e){if(epoch===detailEpoch&&detailCard===card&&sense===selected)toast(e.message);}finally{if(epoch===detailEpoch&&detailCard===card&&sense===selected)clearSenseBusy();}}
async function expand(kind){const epoch=detailEpoch,card=detailCard,selected=sense,pack=sensePack;if(!card||!selected||!pack)return;setSenseBusy(kind==='collocations'?'正在扩展并校对搭配…':'正在扩展并校对四语例句…');try{const d=await api({action:'expand',word:card.en,sense:selected,pack,kind});if(epoch!==detailEpoch||detailCard!==card||sense!==selected)return;const rows=Array.isArray(d?.items)?d.items:[],field=kind==='examples'?'examples':'collocations',old=Array.isArray(pack[field])?[...pack[field]]:[],seen=new Set(old.map(x=>norm([x.zh,x.en,x.de,x.fr].join('|'))));for(const x of rows){const k=norm([x.zh,x.en,x.de,x.fr].join('|'));if(k&&!seen.has(k)){old.push(x);seen.add(k);}}let next={...pack,[field]:old};if(state.settings.autoReview&&rows.length)next=await api({action:'review',word:card.en,sense:selected,pack:next});if(epoch!==detailEpoch||detailCard!==card||sense!==selected)return;sensePack=next;await putPack(card.en,selected.id,next);renderSensePack();toast(rows.length?`候选新增 ${rows.length} 条，已完成终审`:'没有更多足够可靠的新内容');}catch(e){if(epoch===detailEpoch&&detailCard===card&&sense===selected)toast(e.message);}finally{if(epoch===detailEpoch&&detailCard===card&&sense===selected)clearSenseBusy();}}
function enabledLangs(){return state.settings.languageMode==='all'?LANGS:[state.settings.languageMode];}
function tKey(word,sid,lang){return `${norm(word)}|${sid}|${lang}`;}
function track(word,sid,lang,create=false){const k=tKey(word,sid,lang);if(!state.progress[k]&&create)state.progress[k]={reps:0,streak:0,interval:0,due:0,reviews:0,known:false,mastered:false,last:0,recognition:0,production:0,active:true};return state.progress[k]||null;}
function direction(t){const m=state.settings.directionMode;if(m==='recognition'||m==='production')return m;if(m==='alternate')return (t?.reviews||0)%2?'production':'recognition';if((t?.recognition||0)<2)return'recognition';if((t?.production||0)<2)return'production';return (t?.reviews||0)%3===0?'recognition':'production';}
function masteredTrack(t){return !!(t&&(t.mastered||t.known));}
function activeSenseKeys(){const set=new Set();for(const k of Object.keys(state.progress)){const [w,sid]=k.split('|');set.add(`${w}|${sid}`);}return set;}
function conceptMastered(word,sid){return LANGS.every(l=>masteredTrack(track(word,sid,l)));}
function wordStatus(c){const prefix=norm(c.en)+'|',rows=Object.entries(state.progress).filter(([k])=>k.startsWith(prefix));if(!rows.length)return'new';const groups=new Map();for(const [k,t] of rows){const [,sid,lang]=k.split('|');if(!groups.has(sid))groups.set(sid,new Map());groups.get(sid).set(lang,t);}let anyDone=false,allDone=true;for(const m of groups.values()){const ts=LANGS.map(l=>m.get(l)||null);if(ts.some(t=>t?.due&&t.due<=Date.now()&&!masteredTrack(t)))return'due';if(ts.some(masteredTrack))anyDone=true;if(!ts.every(masteredTrack))allDone=false;}if(allDone)return'mastered';if(anyDone)return'partial';return'learning';}
function dueTasks(){const now=Date.now(),out=[];for(const [k,t] of Object.entries(state.progress)){if(!t.active||masteredTrack(t)||!t.due||t.due>now)continue;const [w,sid,lang]=k.split('|'),c=byWord.get(w)||directCard(w);out.push({card:c,sid,lang,due:t.due,newConcept:false});}return out.sort((a,b)=>a.due-b.due);}
function pendingTasks(limit=90){const groups=new Map();for(const [k,t] of Object.entries(state.progress)){if(!t.active)continue;const [w,sid]=k.split('|');groups.set(`${w}|${sid}`,{w,sid});}const out=[];for(const g of groups.values()){for(const lang of enabledLangs()){if(out.length>=limit)return out;let t=track(g.w,g.sid,lang);if(!t){t=track(g.w,g.sid,lang,true);t.active=true;}if(t.active&&!masteredTrack(t)&&!(t.reviews>0)&&!t.due){const c=byWord.get(g.w)||directCard(g.w);out.push({card:c,sid:g.sid,lang,due:0,newConcept:false,pending:true});}}}return out;}
function newConceptCards(){const used=new Set(Object.keys(state.progress).map(k=>k.split('|')[0])),start=Number(state.settings.startRank||2501);return cards.filter(c=>c.rank>=start&&!used.has(norm(c.en))).slice(0,Number(state.settings.dailyNew||0));}
function masteredConceptCount(){const groups=new Map();for(const k of Object.keys(state.progress)){const [w,sid]=k.split('|');groups.set(`${w}|${sid}`,{w,sid});}let n=0;for(const g of groups.values())if(conceptMastered(g.w,g.sid))n++;return n;}
function renderHome(){if(!cards.length)return;$('#todayDue').textContent=Math.min(dueTasks().length,Number(state.settings.reviewCap||90));$('#todayNew').textContent=newConceptCards().length;$('#mastered').textContent=masteredConceptCount();$('#richCount').textContent=state.richWords.length;}

function buildQueue(){const cap=Number(state.settings.reviewCap||90),due=dueTasks().slice(0,cap),pending=pendingTasks(Math.max(0,cap-due.length)),fresh=[];for(const c of newConceptCards())for(const lang of enabledLangs())fresh.push({card:c,sid:null,lang,newConcept:true,due:Infinity});return [...due,...pending,...fresh];}
function setStudyActionLock(v){$$('.rating button').forEach(b=>b.disabled=v);$('#knownCurrent').disabled=v;$('#revealBtn').disabled=v;}
function resetStudySurface(){
  $('#studyLoader').innerHTML='<span class="spinner"></span><span>正在分析常用义项…</span>';
  $('#studyLoader').classList.add('hidden');$('#revealBtn').classList.add('hidden');$('#answer').classList.add('hidden');
  $('#targetAnswer').textContent='—';$('#studySense').innerHTML='';$('#studyPreview').innerHTML='';
  $('#answerSpeakBtn').onclick=null;$('#studySpeakBtn').onclick=null;
  $('#studyCue').textContent='—';$('#cueLabel').textContent='正在准备';$('#recallPrompt').textContent='正在分析当前词的常用义项…';
  for(const id of ['bandBadge','posBadge','langBadge','directionBadge','statusBadge'])$('#'+id).textContent='';
}
async function startStudy(){queue=buildQueue();qi=0;if(!queue.length){toast('今天没有到期任务或新概念');return;}switchView('studyView');await showTask();}
async function showTask(){
  const task=queue[qi]||null, epoch=++studyEpoch;currentTask=task;resetStudySurface();
  if(!task){toast('今日学习完成');switchView('homeView');renderHome();return;}
  const c=task.card;$('#studyLoader').classList.remove('hidden');
  try{
    const a=await ensureAnalysis(c);if(epoch!==studyEpoch||currentTask!==task)return;
    const s=a.senses.find(x=>x.id===task.sid)||a.senses[0];task.sid=s.id;task.sense=s;if(task.newConcept){for(const l of enabledLangs()){const pending=track(c.en,s.id,l,true);pending.active=true;}}
    const t=track(c.en,s.id,task.lang,true),dir=direction(t);task.direction=dir;saveState();
    const hw=s.headwords?.[task.lang]?.primary || (task.lang==='en'?c.en:'—');
    $('#studyProgress').textContent=`${qi+1} / ${queue.length}`;$('#queueLabel').textContent=task.newConcept?'新概念':'到期复习';
    $('#progressBar').style.width=`${Math.round(qi/queue.length*100)}%`;$('#bandBadge').textContent=c.band.label;$('#posBadge').textContent=POS_ZH[s.pos]||s.pos;
    $('#langBadge').textContent=LM[task.lang].name;$('#directionBadge').textContent=dir==='recognition'?'识别：目标语 → 中文':'产出：中文 → 目标语';
    $('#statusBadge').textContent=masteredTrack(t)?'已掌握':t.reviews?'学习中':'新任务';
    if(dir==='recognition'){$('#cueLabel').textContent=`识别 ${LM[task.lang].name}`;$('#studyCue').textContent=hw;$('#recallPrompt').textContent='先说出这个词在当前义项下的准确中文意思；不要借另外两种语言猜。';$('#studySpeakBtn').classList.remove('hidden');$('#studySpeakBtn').onclick=()=>speak(hw,LM[task.lang].locale);}
    else{$('#cueLabel').textContent=`产出 ${LM[task.lang].name}`;$('#studyCue').textContent=s.zhDefinition;$('#recallPrompt').textContent=`根据中文核心义主动说出 ${LM[task.lang].name}；尽量连同冠词或重要词形一起回忆。`;$('#studySpeakBtn').classList.add('hidden');}
    if(epoch!==studyEpoch||currentTask!==task)return;$('#studyLoader').classList.add('hidden');$('#revealBtn').classList.remove('hidden');
  }catch(e){if(epoch!==studyEpoch||currentTask!==task)return;$('#studyLoader').innerHTML=`<span>${esc(e.message)}</span>`;toast('词义分析失败');}
}
async function revealTask(){
  const task=currentTask,epoch=studyEpoch;if(!task||advancing)return;const {card:c,sense:s,lang}=task,hw=s.headwords?.[lang]?.primary||(lang==='en'?c.en:'—');
  $('#targetAnswer').textContent=hw;$('#answerSpeakBtn').onclick=()=>speak(hw,LM[lang].locale);$('#studySense').innerHTML=`<div><small>${esc(s.frequencyLabel||'')}</small><b>${esc(s.zhDefinition)}</b><p>${esc(s.zhExplanation||'')}</p></div>`;
  $('#studyPreview').innerHTML='<div class="loaderBox"><span class="spinner"></span><span>正在准备该义项的高价值搭配与例句…</span></div>';$('#answer').classList.remove('hidden');$('#revealBtn').classList.add('hidden');
  const p=await getPack(c.en,s.id);if(epoch!==studyEpoch||currentTask!==task)return;
  if(!p){ensurePack(c,s).then(x=>{if(epoch===studyEpoch&&currentTask===task&&!$('#answer').classList.contains('hidden'))renderStudyPreview(x,lang,task,epoch);}).catch(()=>{if(epoch===studyEpoch&&currentTask===task&&!$('#answer').classList.contains('hidden'))$('#studyPreview').innerHTML='<p class="muted">详细学习包暂未生成，可在完整词卡中重试。</p>';});}
  else renderStudyPreview(p,lang,task,epoch);
}
function renderStudyPreview(p,lang,task=currentTask,epoch=studyEpoch){if(epoch!==studyEpoch||currentTask!==task)return;const cols=(p?.collocations||[]).filter(x=>String(x.confidence||'high').toLowerCase()==='high').slice(0,2),ex=(p?.examples||[])[0];$('#studyPreview').innerHTML=`<div class="miniPreview">${cols.map(x=>`<p><b>${esc(x.functionZh||x.zh)}</b><br><span>${esc(x.zh)} → ${esc(x[lang])}</span></p>`).join('')}${ex?`<p><b>${esc(ex.scenarioZh||'例句')}</b><br><span>${esc(ex.zh)}<br>${esc(ex[lang])}</span></p>`:''}</div>`;}
async function advanceTask(mutator){if(!currentTask||advancing)return;advancing=true;setStudyActionLock(true);const task=currentTask;++studyEpoch;try{mutator(task);saveState();qi++;renderHome();await showTask();}finally{advancing=false;setStudyActionLock(false);}}
function rate(kind){return advanceTask(task=>{const {card:c,sid,lang,direction:dir}=task,t=track(c.en,sid,lang,true),old=Number(t.interval||0);let days;if(kind==='again'){t.streak=0;t.reps=Math.max(0,t.reps-1);days=10/(60*24);if(dir==='recognition')t.recognition=Math.max(0,(t.recognition||0)-1);else t.production=Math.max(0,(t.production||0)-1);}else{t.streak++;t.reps++;if(dir==='recognition')t.recognition=(t.recognition||0)+1;else t.production=(t.production||0)+1;days=kind==='hard'?(old?Math.max(1,old*1.35):1):kind==='good'?(old?Math.max(2,old*2.35):2):(old?Math.max(4,old*3.2):4);}t.interval=Math.round(days*100)/100;t.due=Date.now()+days*DAY;t.last=Date.now();t.reviews++;t.known=false;t.active=true;t.mastered=t.reps>=Number(state.settings.masterReps)&&t.streak>=3&&t.interval>=Number(state.settings.masterDays)&&(t.recognition||0)>=2&&(t.production||0)>=2;state.reviews++;rememberRecent(c.en,sid,lang);});}
function markKnown(){return advanceTask(task=>{const t=track(task.card.en,task.sid,task.lang,true);t.known=true;t.mastered=true;t.last=Date.now();t.due=0;t.active=true;rememberRecent(task.card.en,task.sid,task.lang);});}
function rememberRecent(w,sid,lang){state.recent=[{w:norm(w),sid,lang,t:Date.now()},...state.recent.filter(x=>!(x.w===norm(w)&&x.sid===sid&&x.lang===lang))].slice(0,30);}

function morphs(q){const w=norm(q),s=new Set([w]),irr={went:'go',gone:'go',children:'child',people:'person',men:'man',women:'woman',teeth:'tooth',feet:'foot',mice:'mouse',criteria:'criterion',phenomena:'phenomenon',analyses:'analysis',indices:'index',better:'good',best:'good',worse:'bad',worst:'bad'};if(irr[w])s.add(irr[w]);if(!/^[a-z'-]+$/.test(w))return s;if(w.endsWith('ied'))s.add(w.slice(0,-3)+'y');if(w.endsWith('ies'))s.add(w.slice(0,-3)+'y');if(w.endsWith('ed')){const x=w.slice(0,-2);s.add(x);s.add(x+'e');if(x.length>2&&x.at(-1)===x.at(-2))s.add(x.slice(0,-1));}if(w.endsWith('ing')){const x=w.slice(0,-3);s.add(x);s.add(x+'e');if(x.length>2&&x.at(-1)===x.at(-2))s.add(x.slice(0,-1));}if(w.endsWith('es')){s.add(w.slice(0,-2));s.add(w.slice(0,-1));}if(w.endsWith('s')&&w.length>3)s.add(w.slice(0,-1));return s;}
function searchScore(c,q){if(!q)return 0;const nq=norm(q),en=norm(c.en),ms=morphs(nq);if(en===nq)return 0;if(ms.has(en))return 3;if(en.startsWith(nq))return 8;if(en.includes(nq))return 15;if(c.searchText.includes(nq))return 30;return Infinity;}
function matchesStatus(c,st){if(st==='all')return true;if(st==='favorite')return !!state.favorites[norm(c.en)];if(st==='rich')return state.richWords.includes(norm(c.en));return wordStatus(c)===st;}
function filtered(){const q=$('#searchInput').value.trim();filters.q=q;let a=[];for(const c of cards){if(filters.band!=='all'&&c.band.id!==filters.band)continue;if(filters.pos!=='all'&&c.pos!==filters.pos)continue;if(!matchesStatus(c,filters.status))continue;const sc=searchScore(c,q);if(sc<Infinity)a.push({c,sc});}if(filters.sort==='alpha')a.sort((x,y)=>x.c.en.localeCompare(y.c.en));else if(filters.sort==='rank')a.sort((x,y)=>x.c.rank-y.c.rank);else if(filters.sort==='recent'){const rm=new Map(state.recent.map((x,i)=>[x.w,i]));a.sort((x,y)=>(rm.get(norm(x.c.en))??9999)-(rm.get(norm(y.c.en))??9999)||x.c.rank-y.c.rank);}else a.sort((x,y)=>x.sc-y.sc||x.c.rank-y.c.rank);return a.map(x=>x.c);}
async function resultHTML(c){const a=await getAnalysis(c.en),s=a?.senses?.[0];return `<button class="resultCard" data-rank="${c.rank}" data-word="${esc(c.en)}"><div><span class="rank">${c.rank?'#'+c.rank:'AI'}</span><strong>${esc(c.en)}</strong><small>${esc(POS_ZH[c.pos]||c.pos)} · ${esc(c.band.label)} · ${state.richWords.includes(norm(c.en))?'AI 已校正':'待 AI 分析'}</small></div><div class="langs">${s?`<span>中 ${esc(s.zhDefinition)}</span><span>DE ${esc(s.headwords?.de?.primary||'—')}</span><span>FR ${esc(s.headwords?.fr?.primary||'—')}</span>`:'<span>打开后由 DeepSeek 识别常用义项并校正中德法对应</span>'}</div></button>`;}
async function renderSearch(){const epoch=++searchEpoch;filters.status=$('#statusFilter').value;filters.pos=$('#posFilter').value;filters.sort=$('#sortFilter').value;const arr=filtered(),size=Number(state.settings.pageSize)||40,pages=Math.max(1,Math.ceil(arr.length/size));filters.page=Math.min(Math.max(1,filters.page),pages);const start=(filters.page-1)*size,vis=arr.slice(start,start+size);$('#resultSummary').textContent=`共 ${arr.length.toLocaleString()} 个结果 · 显示 ${arr.length?start+1:0}–${Math.min(start+size,arr.length)}`;$('#pageInfo').textContent=`第 ${filters.page} / ${pages} 页`;$('#prevPage').disabled=filters.page<=1;$('#nextPage').disabled=filters.page>=pages;$('#pager').classList.toggle('hidden',!arr.length);$('#searchResults').innerHTML=vis.length?'<div class="loaderBox"><span class="spinner"></span><span>正在读取已缓存 AI 词义…</span></div>':'<div class="empty">没有词库匹配</div>';if(vis.length){const html=await Promise.all(vis.map(resultHTML));if(epoch!==searchEpoch)return;$('#searchResults').innerHTML=html.join('');$$('.resultCard').forEach(b=>b.onclick=()=>openDetail(b.dataset.rank!=='0'?byRank.get(Number(b.dataset.rank)):directCard(b.dataset.word)));}if(epoch===searchEpoch)renderDirectLookup(arr.length);}
function renderDirectLookup(total){const q=$('#searchInput').value.trim();const valid=/^[A-Za-z][A-Za-z' -]{1,60}$/.test(q);$('#directLookup').innerHTML=valid&&!cards.some(c=>norm(c.en)===norm(q))?`<button class="directLookup" id="directLookupBtn"><b>AI 识别词形 / 查询 “${esc(q)}”</b><span>自动判断是否为变形并还原到词典原形；不在 10,000 底库也可建立完整多义词卡</span></button>`:'';$('#directLookupBtn')?.addEventListener('click',()=>openDetail(directCard(q)));}
function resetFilters(){filters={band:'all',status:'all',pos:'all',sort:'relevance',q:'',page:1};$('#searchInput').value='';$('#statusFilter').value='all';$('#posFilter').value='all';$('#sortFilter').value='relevance';$$('.chip').forEach(b=>b.classList.toggle('active',b.dataset.band==='all'));renderSearch();}

async function openDetail(c){if(!c)return;const epoch=++detailEpoch;detailCard=c;analysis=null;sense=null;sensePack=null;$('#detailWord').textContent=c.en;$('#favoriteBtn').textContent=state.favorites[norm(c.en)]?'★':'☆';$('#detailBadges').innerHTML=`<span>${c.rank?'#'+c.rank:'AI 直接查询'}</span><span>${esc(POS_ZH[c.pos]||c.pos)}</span><span>${esc(c.band.label)}</span>`;$('#detailBackdrop').classList.remove('hidden');document.body.style.overflow='hidden';$('#detailLoading').classList.remove('hidden');$('#detailError').classList.add('hidden');$('#analysisBox').classList.add('hidden');$('#sensePack').classList.add('hidden');try{const a=await ensureAnalysis(c);if(epoch!==detailEpoch||detailCard!==c)return;if(c.custom&&a?.word&&norm(a.word)!==norm(c.en)){const input=c.en;c.en=String(a.word);c.searchText=norm(c.en);$('#detailWord').textContent=c.en;$('#detailBadges').innerHTML=`<span>AI 词形还原</span><span>${esc(input)} → ${esc(c.en)}</span>`;}analysis=a;renderAnalysis();await selectSense(a.senses[0].id,true,epoch);}catch(e){if(epoch!==detailEpoch||detailCard!==c)return;$('#detailLoading').classList.add('hidden');$('#detailError').classList.remove('hidden');$('#detailError').innerHTML=`<b>词义分析失败</b><p>${esc(e.message)}</p><button class="secondary" id="retryAnalysis">重试</button>`;$('#retryAnalysis').onclick=()=>openDetail(c);}}
function closeDetail(){detailEpoch++;$('#detailBackdrop').classList.add('hidden');document.body.style.overflow='';detailCard=null;analysis=null;sense=null;sensePack=null;}
function renderAnalysis(){$('#detailLoading').classList.add('hidden');$('#analysisBox').classList.remove('hidden');$('#wordNotes').textContent=analysis.wordLevelNotesZh||'';$('#senseTabs').innerHTML=analysis.senses.map((s,i)=>`<button data-sid="${esc(s.id)}" class="senseTab ${i===0?'active':''}"><b>${i+1}</b><span>${esc(s.zhDefinition)}</span><small>${esc(s.frequencyLabel||'')}</small></button>`).join('');$$('.senseTab').forEach(b=>b.onclick=()=>selectSense(b.dataset.sid,false));}
async function selectSense(id,auto,existingEpoch=null){const epoch=existingEpoch??++detailEpoch,card=detailCard,a=analysis;if(!card||!a)return;clearSenseBusy();const selected=a.senses.find(x=>x.id===id)||a.senses[0];sense=selected;sensePack=null;$$('.senseTab').forEach(b=>b.classList.toggle('active',b.dataset.sid===selected.id));$('#senseFreq').textContent=`${selected.frequencyLabel||''} · ${POS_ZH[selected.pos]||selected.pos}`;$('#senseZh').textContent=selected.zhDefinition||'—';$('#senseExplain').textContent=selected.zhExplanation||'';$('#senseMeta').textContent=[selected.register,selected.domain,selected.notesZh].filter(Boolean).join(' · ');$('#headwordGrid').innerHTML=['en','de','fr'].map(l=>{const h=selected.headwords?.[l]||{};return `<div class="headword"><small>${LM[l].name}</small><b>${esc(h.primary||'—')}</b><p>${(h.alternatives||[]).map(esc).join(' · ')}</p>${h.noteZh?`<em>${esc(h.noteZh)}</em>`:''}<button class="miniSpeak" data-speak="${esc(h.primary||'')}" data-lang="${LM[l].locale}">🔊</button></div>`;}).join('');bindSpeech($('#headwordGrid'));$('#senseContexts').innerHTML=(selected.typicalContextsZh||[]).map(x=>`<span>${esc(x)}</span>`).join('');$('#sensePack').classList.add('hidden');const p=await getPack(card.en,selected.id);if(epoch!==detailEpoch||detailCard!==card||analysis!==a||sense!==selected)return;sensePack=p;renderDetailProgress();if(p){renderSensePack();$('#loadSenseBtn').textContent='重新生成此义项';}else{$('#sensePack').classList.add('hidden');$('#loadSenseBtn').textContent='生成此义项完整学习包';if(auto)await loadSensePack(epoch,card,selected);}}
async function loadSensePack(epoch=detailEpoch,card=detailCard,selected=sense){if(!card||!selected)return;setSenseBusy('正在生成词形、词族、近义差异、搭配和四语例句…');try{const p=await ensurePack(card,selected,true);if(epoch!==detailEpoch||detailCard!==card||sense!==selected)return;sensePack=p;renderSensePack();$('#loadSenseBtn').textContent='重新生成此义项';toast(sensePack?.audit?.reviewed?'生成并二次校对完成':'学习包生成完成');}catch(e){if(epoch===detailEpoch&&detailCard===card&&sense===selected)toast(e.message);}finally{if(epoch===detailEpoch&&detailCard===card&&sense===selected)clearSenseBusy();}}
function setSenseBusy(msg){$('#loadSenseBtn').disabled=true;$('#loadSenseBtn').textContent=msg;}
function clearSenseBusy(){$('#loadSenseBtn').disabled=false;$('#loadSenseBtn').textContent=sensePack?'重新生成此义项':'生成此义项完整学习包';}
function formHTML(forms,l){const h=sensePack?.headwords?.[l]||{};return `<div class="formCol"><h3>${LM[l].name}</h3><b>${esc(h.word||sense?.headwords?.[l]?.primary||'—')}</b>${h.grammar?`<p class="grammar">${esc(h.grammar)}</p>`:''}<div>${(forms||[]).map(x=>`<p><small>${esc(x.label)}</small><span>${esc(x.form)}</span>${x.noteZh?`<em>${esc(x.noteZh)}</em>`:''}</p>`).join('')}</div></div>`;}
function alignedRows(rows,kind){if(!Array.isArray(rows)||!rows.length)return'<div class="empty small">暂无可靠内容</div>';return `<div class="alignedHeader"><span>中文</span><span>EN</span><span>DE</span><span>FR</span></div>`+rows.map(x=>`<div class="alignedRow"><div><b>${esc(x.functionZh||x.nuanceZh||x.zh||'')}</b><span>${esc(x.zh||'')}</span>${x.differenceZh?`<em>${esc(x.differenceZh)}</em>`:''}</div><div>${esc(x.en||'')}</div><div>${esc(x.de||'')}</div><div>${esc(x.fr||'')}</div>${x.noteZh?`<small>${esc(x.noteZh)}</small>`:''}${x.register?`<small>${esc(x.register)}</small>`:''}</div>`).join('');}
function renderSensePack(){if(!sensePack)return;$('#sensePack').classList.remove('hidden');$('#auditBadge').textContent=sensePack.audit?.reviewed?'V4 Pro 终审✓':'Flash 自检';$('#formsGrid').innerHTML=LANGS.map(l=>formHTML(sensePack.forms?.[l],l)).join('');$('#familiesTable').innerHTML=alignedRows(sensePack.families,'families');$('#synonymsTable').innerHTML=alignedRows(sensePack.synonyms,'synonyms');$('#antonymsTable').innerHTML=alignedRows(sensePack.antonyms,'antonyms');const allCols=sensePack.collocations||[],high=allCols.filter(x=>String(x.confidence||'high').toLowerCase()==='high'),medium=allCols.filter(x=>String(x.confidence||'').toLowerCase()==='medium');$('#collocationsTable').innerHTML=alignedRows(high,'collocations')+(medium.length?`<details class="mediumEvidence"><summary>查看 ${medium.length} 条中置信度扩展（不计入核心记忆）</summary><div class="alignedTable">${alignedRows(medium,'collocations')}</div></details>`:'');$('#examplesDeck').innerHTML=(sensePack.examples||[]).map((x,i)=>`<article class="exampleCard"><header><b>${i+1}. ${esc(x.scenarioZh||'情境')}</b>${x.noteZh?`<span>${esc(x.noteZh)}</span>`:''}</header><p><b>中</b>${esc(x.zh)}</p><p><b>EN</b>${esc(x.en)}</p><p><b>DE</b>${esc(x.de)}</p><p><b>FR</b>${esc(x.fr)}</p></article>`).join('')||'<div class="empty small">暂无可靠例句</div>';$('#usageNotes').innerHTML=(sensePack.usageNotes||[]).map(x=>`<p>${esc(x)}</p>`).join('')||'<p class="muted">暂无特别限制</p>';renderDetailProgress();}
function renderDetailProgress(){if(!sense){$('#detailProgress').innerHTML='<p class="muted">请选择义项</p>';return;}$('#detailProgress').innerHTML=LANGS.map(l=>{const t=track(detailCard.en,sense.id,l);return `<div class="trackRow"><b>${LM[l].short}</b><span>${t?.known?'已认识':t?.mastered?'已掌握':t?.reviews?'学习中':'未加入'}</span><small>识别 ${t?.recognition||0} · 产出 ${t?.production||0} · 间隔 ${t?.interval||0}d</small></div>`;}).join('');}
function addSenseStudy(){if(!detailCard||!sense)return;for(const l of enabledLangs()){const t=track(detailCard.en,sense.id,l,true);t.active=true;t.due=Date.now();}saveState();renderDetailProgress();renderHome();toast('该义项已加入复习');}
function toggleFavorite(){if(!detailCard)return;const w=norm(detailCard.en);state.favorites[w]=!state.favorites[w];if(!state.favorites[w])delete state.favorites[w];saveState();$('#favoriteBtn').textContent=state.favorites[w]?'★':'☆';}

function renderStats(){const data={en:{},de:{},fr:{}};for(const l of LANGS){const ts=Object.entries(state.progress).filter(([k])=>k.endsWith('|'+l)).map(([,t])=>t);data[l]={active:ts.length,mastered:ts.filter(masteredTrack).length,due:ts.filter(t=>!masteredTrack(t)&&t.due&&t.due<=Date.now()).length,reviews:ts.reduce((a,t)=>a+(t.reviews||0),0)};}$('#languageStats').innerHTML=LANGS.map(l=>`<div class="card langStat"><header><h2>${LM[l].name}</h2><span>${LM[l].short}</span></header><div><b>${data[l].mastered}</b><small>掌握义项</small></div><div><b>${data[l].due}</b><small>到期</small></div><div><b>${data[l].reviews}</b><small>评分</small></div></div>`).join('');const base=new Date();base.setHours(0,0,0,0);const bins=Array(7).fill(0);for(const t of Object.values(state.progress)){if(masteredTrack(t)||!t.due)continue;const d=Math.floor((t.due-base.getTime())/DAY);if(d>=0&&d<7)bins[d]++;}const mx=Math.max(1,...bins);$('#forecast').innerHTML=bins.map((n,i)=>`<div><i style="height:${Math.max(5,n/mx*100)}%"></i><b>${n}</b><span>${i?'+'+i+'天':'今天'}</span></div>`).join('');$('#recentList').innerHTML=state.recent.slice(0,10).map(x=>`<button class="miniItem" data-word="${esc(x.w)}"><b>${esc(x.w)}</b><span>${LM[x.lang]?.short||x.lang} · ${new Date(x.t).toLocaleDateString()}</span></button>`).join('')||'<div class="empty small">还没有学习记录</div>';$$('.miniItem').forEach(b=>b.onclick=()=>openDetail(byWord.get(b.dataset.word)||directCard(b.dataset.word)));}

function loadSettings(){const s=state.settings;$('#dailyNew').value=s.dailyNew;$('#reviewCap').value=s.reviewCap;$('#startBand').value=String(s.startRank);$('#languageMode').value=s.languageMode;$('#directionMode').value=s.directionMode;$('#masterReps').value=s.masterReps;$('#masterDays').value=s.masterDays;$('#pageSize').value=String(s.pageSize);$('#autoReview').checked=!!s.autoReview;}
function clamp(v,a,b){v=parseInt(v,10);return Number.isFinite(v)?Math.max(a,Math.min(b,v)):a;}
function saveSettings(){state.settings.dailyNew=clamp($('#dailyNew').value,0,30);state.settings.reviewCap=clamp($('#reviewCap').value,10,300);state.settings.startRank=Number($('#startBand').value);state.settings.languageMode=$('#languageMode').value;state.settings.directionMode=$('#directionMode').value;state.settings.masterReps=clamp($('#masterReps').value,3,20);state.settings.masterDays=clamp($('#masterDays').value,14,180);state.settings.pageSize=Number($('#pageSize').value)||40;state.settings.autoReview=$('#autoReview').checked;saveState();renderHome();toast('设置已保存');}
function exportData(){const b=new Blob([JSON.stringify({app:'LexiBridge4',version:10,exportedAt:new Date().toISOString(),state},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`LexiBridge4_v10_${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
async function importData(f){try{const d=JSON.parse(await f.text());if(!d?.state?.progress)throw 0;const b=defaultState();state={...b,...d.state,settings:{...b.settings,...d.state.settings}};saveState();renderHome();toast('学习记录已导入');}catch{toast('备份文件无效');}}
function resetAll(){if(!confirm('确定清空全部学习记录？AI 词卡缓存不会删除。'))return;const keep=state.richWords;state=defaultState();state.richWords=keep;saveState();renderHome();toast('学习记录已清空');}
function speak(text,lang){if(!text||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=lang;speechSynthesis.speak(u);}
function bindSpeech(root=document){root.querySelectorAll('[data-speak]').forEach(b=>b.onclick=()=>speak(b.dataset.speak,b.dataset.lang));}
function applyTheme(){const m=state.settings.theme;document.documentElement.dataset.theme=m==='system'?(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'):m;}
function toggleTheme(){state.settings.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';saveState();applyTheme();}
function switchView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));window.scrollTo({top:0,behavior:'instant'});if(id==='browseView')renderSearch();if(id==='statsView')renderStats();if(id==='settingsView')loadSettings();}
function openStatus(st){filters.status=st==='rich'?'rich':st;$('#statusFilter').value=filters.status==='new'?'new':filters.status==='due'?'due':filters.status==='mastered'?'mastered':filters.status==='rich'?'rich':'all';switchView('browseView');}
async function forceUpdate(){toast('正在刷新最新版…');try{const rs=await navigator.serviceWorker?.getRegistrations?.()||[];for(const r of rs)await r.update();const ks=await caches.keys();await Promise.all(ks.filter(k=>k.startsWith('lexibridge4-')).map(k=>caches.delete(k)));}catch{}setTimeout(()=>location.replace(`${location.pathname}?v=${Date.now()}`),350);}
function registerSW(){if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('./sw.js?v=10').catch(()=>{});}

function bind(){$$('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-open-status]').forEach(b=>b.onclick=()=>openStatus(b.dataset.openStatus));$('#startBtn').onclick=startStudy;$('#endStudy').onclick=()=>switchView('homeView');$('#revealBtn').onclick=revealTask;$$('.rating button').forEach(b=>b.onclick=()=>rate(b.dataset.rate));$('#knownCurrent').onclick=markKnown;$('#openStudyDetail').onclick=()=>currentTask&&openDetail(currentTask.card);$('#searchInput').oninput=()=>{filters.page=1;renderSearch();};$('#clearSearch').onclick=()=>{$('#searchInput').value='';filters.page=1;renderSearch();};$$('.chip').forEach(b=>b.onclick=()=>{filters.band=b.dataset.band;filters.page=1;$$('.chip').forEach(x=>x.classList.toggle('active',x===b));renderSearch();});for(const id of ['statusFilter','posFilter','sortFilter'])$('#'+id).onchange=()=>{filters.page=1;renderSearch();};$('#resetFilters').onclick=resetFilters;$('#prevPage').onclick=()=>{filters.page--;renderSearch();};$('#nextPage').onclick=()=>{filters.page++;renderSearch();};$('#pageInfo').onclick=()=>{const arr=filtered(),pages=Math.max(1,Math.ceil(arr.length/(state.settings.pageSize||40))),v=Number(prompt(`输入页码 1–${pages}`,filters.page));if(v>=1&&v<=pages){filters.page=v;renderSearch();}};$('#jumpRankBtn').onclick=()=>{const n=Number(prompt('输入词库序号 1–10000'));if(byRank.get(n))openDetail(byRank.get(n));};$('#closeDetail').onclick=closeDetail;$('#detailBackdrop').onclick=e=>{if(e.target===$('#detailBackdrop'))closeDetail();};$('#favoriteBtn').onclick=toggleFavorite;$('#loadSenseBtn').onclick=()=>loadSensePack();$('#addSenseStudyBtn').onclick=addSenseStudy;$('#reviewPackBtn').onclick=reviewPack;$('#expandCollocationsBtn').onclick=()=>expand('collocations');$('#expandExamplesBtn').onclick=()=>expand('examples');$('#saveSettings').onclick=saveSettings;$('#exportBtn').onclick=exportData;$('#importInput').onchange=e=>e.target.files[0]&&importData(e.target.files[0]);$('#resetBtn').onclick=resetAll;$('#themeBtn').onclick=toggleTheme;$('#updateBtn').onclick=forceUpdate;$('#backendPill').onclick=checkBackend;}
function init(){applyTheme();bind();buildCards();registerSW();}
document.addEventListener('DOMContentLoaded',init);
})();